import Head from "next/head";
import fs from "fs/promises";
import path from "path";

import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home(props) {
  const bookList = props.books.map((book) => (
    <li key={book.ISBN} className={styles["list-items"]}>
      <Link href={`/${book.ISBN}`}>{book.name}</Link>
    </li>
  ));

  return (
    <div className={styles.container}>
      <Head>
        <title>Pre-rendering</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <ul className={styles["books"]}>{bookList}</ul>
    </div>
  );
}

export async function getStaticProps() {
  const filePath = path.join(process.cwd(), "backend-file.json");
  const jsonData = await fs.readFile(filePath);
  const data = JSON.parse(jsonData);
  console.log("HIII", data.books);

  if (!data) {
    return {
      redirect: {
        destination: "/no-data",
      },
    };
  }

  if (data.books.length === 0) {
    return { notFound: true };
  }

  return {
    props: {
      books: data.books,
    },
    revalidate: 10, // every incoming req, create once every 10 seconds
    //notFound: true, // this return 404 error page instead of normal page
    // redirect: {}
  };
}
